import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";
import { Direction } from "radix-ui";
import Navigation from "@/components/layout/Navigation";
import { Providers } from "./Providers";


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const irSansFont = localFont({
  src: [
    {
      path: "./fonts/IRAN_Sans.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/IRAN_Sans_Bold.ttf",
      weight: "700",
      style: "bold",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' dir="rtl">
  
        <body className={`${irSansFont.className} antialiased`}>
         <Providers>{children}</Providers>
        </body>
    </html>
  );
}
